workflows:
  full-workflow:
    name: CuentaContable Multi-Platform Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    working_directory: mobile_app
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'master'
          include: true
    scripts:
      - name: Initialize iOS & Get Packages
        script: |
          flutter create . --platforms=ios
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios && pod install
      - name: Build Android APK
        script: |
          flutter build apk --release
      - name: Build iOS (Unsigned IPA)
        script: |
          # Compilar el binario puro de iOS
          flutter build ios --release --no-codesign
          
          # Crear la estructura manual para Sideloadly
          mkdir -p build/ios/ipa/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          
          # Comprimirlo a formato .ipa
          cd build/ios/ipa
          zip -qr CuentaContable.ipa Payload
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/ios/ipa/CuentaContable.ipa
    publishing:
      email:
        recipients:
          - josebacilio2004@gmail.com
        notify:
          success: true
          failure: true
